# Generated by Django 4.1.13 on 2024-01-05 15:28

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import utils.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('name', models.CharField(max_length=100)),
                ('username', models.CharField(blank=True, max_length=90, null=True, unique=True, validators=[utils.utils.username_validator])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/user_avatar')),
                ('description', models.TextField(blank=True, max_length=70, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='PrivateMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('users', models.ManyToManyField(related_name='pv_user', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'PrivateMessage_DB',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=6)),
                ('expiration_time', models.DateTimeField(blank=True, null=True)),
                ('phone_no', models.CharField(max_length=11, unique=True, validators=[utils.utils.phone_validator])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='phone_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Phone_DB',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('body', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/message_picture')),
                ('Private_message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.privatemessage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Message_DB',
                'ordering': ('-timestamp',),
            },
        ),
        migrations.CreateModel(
            name='LoginVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='index_visit', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'LoginVisit_DB',
            },
        ),
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/group_avatar')),
                ('title', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=65, null=True)),
                ('admin', models.ManyToManyField(related_name='group_admin', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(db_index=True, related_name='group_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Groups_DB',
            },
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(db_index=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('picture', models.ImageField(blank=True, db_index=True, null=True, upload_to='images/group_message_picture')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.groups')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GroupMessage_DB',
                'ordering': ('-timestamp',),
            },
        ),
    ]
