# Generated by Django 4.2.7 on 2023-12-07 21:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Groups',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='images/group_avatar')),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(blank=True, max_length=65, null=True)),
                ('admin', models.ManyToManyField(related_name='group_admin', to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(db_index=True, related_name='group_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Groups_DB',
            },
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(db_index=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.groups')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'GroupMessage_DB',
                'ordering': ('-timestamp',),
            },
        ),
    ]
