# Generated by Django 4.2 on 2023-12-23 13:49

from django.db import migrations, models
import utils.utils


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_user_name_alter_user_role_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groups',
            old_name='name',
            new_name='title',
        ),
        migrations.AlterField(
            model_name='phone',
            name='phone_no',
            field=models.CharField(max_length=11, unique=True, validators=[utils.utils.phone_validator]),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=90, null=True, unique=True, validators=[utils.utils.username_validator]),
        ),
    ]
