# Generated by Django 4.1.13 on 2024-01-05 21:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_message_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'ordering': ('-timestamp',)},
        ),
        migrations.AddField(
            model_name='groups',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
