# Generated by Django 4.2 on 2023-12-26 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_rename_name_groups_title_alter_phone_phone_no_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='groupmessage',
            old_name='sender',
            new_name='user',
        ),
    ]
