# Generated by Django 4.2 on 2023-12-29 11:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_rename_sender_groupmessage_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='loginvisit',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
