# Generated by Django 4.2 on 2023-12-31 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_alter_user_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='picture',
            field=models.ImageField(blank=True, db_index=True, null=True, upload_to='images/group_message_picture'),
        ),
        migrations.AddField(
            model_name='message',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/message_picture'),
        ),
    ]
